# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"

  config.vm.provision "file", source: "index.html", destination: "~/index.html"
  config.vm.provision "file", source: "index.php", destination: "~/index.php"
  config.vm.provision "file", source: "web1.conf", destination: "~/web1.conf"
  config.vm.provision "file", source: "web2.conf", destination: "~/web2.conf"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    apt-get install -y php

    mkdir /var/www/web1 /var/www/web2
    rm -r /var/www/html
    mv /vagrant/index.html /var/www/web1
    mv /vagrant/index.php /var/www/web2
    chmod 666 /var/www/web1/index.html /var/www/web2/index.php
    
    echo "Listen 81" >> /etc/apache2/ports.conf
    rm /etc/apache2/sites-available/000-default.conf
    mv /vagrant/web1.conf /etc/apache2/sites-available/web1.conf
    mv /vagrant/web2.conf /etc/apache2/sites-available/web2.conf
    chmod 666 /etc/apache2/sites-available/web2.conf /etc/apache2/sites-available/web1.conf
    
    sudo a2ensite web1
    sudo a2ensite web2
    sudo service apache2 restart
  SHELL

end
