# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 81, host: 8081, host_ip: "127.0.0.1"
  config.vm.provision "file", source: "index.html", destination: "~/index.html"
  config.vm.provision "file", source: "index.php", destination: "~/index.php"
  config.vm.provision "file", source: "html.conf", destination: "~/html.conf"
  config.vm.provision "file", source: "php.conf", destination: "~/php.conf"


  config.vm.define "web" do |web|
      web.vm.network "private_network", ip: "192.168.56.5"

      web.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "web.yaml"
          ansible.inventory_path = "inventory.ini"

      end
  end 
end
