- name: Web provision
  hosts: web
  become: yes

  tasks:
  - name: Install packages
    apt:
      pkg: 
        - apache2
        - php
      state: present
  
  - name: Add index.html
    copy:
      src: /vagrant/index.html
      dest: /var/www/html/
      mode: '0666'
  
  - name: Add dinamic site directory
    file:
      path: /var/www/php
      state: directory

  - name: Add index.php
    copy:
      src: /vagrant/index.php
      dest: /var/www/php/
      mode: '0666'

  - name: Add listening 81 port
    lineinfile:
      path: "/etc/apache2/ports.conf"
      line: 'Listen 81'

  - name: Add static site config
    copy:
      src: /vagrant/html.conf
      dest: /etc/apache2/sites-available
      mode: '0666'

  - name: Add dynamic site config
    copy:
      src: /vagrant/php.conf
      dest: /etc/apache2/sites-available
      mode: '0666'

  - name: Enable static site 
    shell: a2ensite html 

  - name: Enable static dynamic site  
    shell: a2ensite php  

  - name: Restart apache
    systemd:
      name: apache2
      state: restarted